spring:
  application:
    name: mydataagent
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
