spring:
  application:
    name: mydataagent
  task:
    execution:
      pool:
        core-size: 10
        max-size: 100
        queue-capacity: 500
      thread-name-prefix: "ConversationExcutor-"
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: testdb
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        enabled: true
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

      embedding:
        enabled: true
        options:
          model: text-embedding-ada-002


    vectorstore:
      weaviate:
        host: izfbxjnisyzzpqnai62w.c0.asia-southeast1.gcp.weaviate.cloud
        api-key: AVm6AIvYXFDUJMQYK8pLRsSC4sQ0hEqlxCv0
        scheme: https
        object-class: "TechnicalGuideline"
        consistency-level: one

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
